---
version: 2
updates:
  - package-ecosystem: gomod
    directory: /golang-dns-gutcheck
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /java-spring-boot-web
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /nodejs-web
    schedule:
      interval: daily
