version: 2
updates:
- package-ecosystem: npm
  directory: "/nodejs-web"
  schedule:
    interval: daily
    time: '11:00'
  open-pull-requests-limit: 10
- package-ecosystem: maven
  directory: "/java-spring-boot-web"
  schedule:
    interval: daily
    time: '11:00'
  open-pull-requests-limit: 10
