version: 1
update_configs:
- package_manager: "java:maven"
  directory: "/java-spring-boot-web"
  update_schedule: "live"
- package_manager: "javascript"
  directory: "/nodejs-web"
  update_schedule: "live"
